<?php

namespace Awcodes\FilamentOembed;

use Filament\Support\Assets\Css;
use Filament\Support\Facades\FilamentAsset;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class OembedServiceProvider extends PackageServiceProvider
{
    public static string $name = 'filament-oembed';

    public function configurePackage(Package $package): void
    {
        $package->name(static::$name)
            ->hasViews()
            ->hasAssets()
            ->hasTranslations();
    }

    public function packageBooted()
    {
        parent::packageBooted(); // TODO: Change the autogenerated stub

        FilamentAsset::register([
            Css::make(
                'plugin-filament-oembed',
                __DIR__.'/../resources/dist/filament-oembed.css'
            ),
        ], 'awcodes/filament-oembed');
    }
}
